version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_DB: springbootdb
      POSTGRES_USER: hackaton
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  springboot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app_container
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/springbootdb
      SPRING_DATASOURCE_USERNAME: hackaton
      SPRING_DATASOURCE_PASSWORD: 12345678

volumes:
  postgresql_data: