spring:
  application:
  name: hackaton
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: hackaton
    password: 12345678
    url: "jdbc:postgresql://postgresql:5432/springbootdb"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

